spring:
  application:
    name: user

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:user}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:pstgrs}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml
    default-schema: public
    liquibase-schema: public
    drop-first: false

    jpa:
      hibernate:
        ddl-auto: none

  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      group-id: ${KAFKA_CONSUMER_GROUP_ID:success-confirmation-group}
server:
  port: ${SERVER_PORT:8082}

user:
  scheduler:
    phone-confirm:
      enabled: "true"
      fixed-rate-ms: 5000

confirmation:
  client:
    base-url: http://localhost:8084
